version: "3.3"

services:
  app:
    image: link-page
    ports: 
      - "3000:3000"
    volumes:
      - ./app/src/:/usr/src/app/src/
      - ./app/resources:/usr/src/app/resources
    networks:
      - net
  redis:
    image: redis
    networks: 
      - net

networks: 
  net: